name: Frontend Test
run-name: Frontend Test
on: [push]
jobs:
  Frontend-Test:
    runs-on: ubuntu-latest
    steps:              

      - name: React Build Test
        run: |
          ls
        working-directory: ${{ env.working-directory }}/frontend

