name: Frontend Test
run-name: Frontend Test
on: [push]
jobs:
  SQL-Test:
    runs-on: ubuntu-latest
    steps:              

      - name: React Build Test
        run: |
          npm install react-scripts
          npm run build
        working-directory: ./frontend
